config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :posts do
    collection do
     get 'me'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/animaux/:slug', to: 'posts#species', as: :species_posts
  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  resources :users, only: [:new, :create] do
  	member do
  		get 'confirm'
  	end
  end
  # Sessions
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :pets do
    resource :subscriptions, only: [:create, :destroy]
  end

  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :species, except: [:show]
  end
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_and_belongs_to_many :pets

  has_image :image, resize: '940x530', formats: {
    thumb: '360x200'
  }

  validates :name, :content, :pet_ids, presence: true
  validates :image_file, presence: true, on: :create

end

app/models/user.rb
class User < ApplicationRecord

	has_many :pets, dependent: :destroy
	has_many :posts, dependent: :destroy
	has_many :subscriptions
	has_many :followed_pets, through: :subscriptions, source: :pet

	has_secure_password
	has_secure_token :confirmation_token
	has_secure_token :recover_password

	validates :username, 
	format: {with: /\A[a-zA-Z0-9_]{2,20}\z/, message: 'ne doit contenir que des caractères alphanumériques ou underscores.'},
	uniqueness: {case_sensitive: false}

	validates :email,
	format: {with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i},
	uniqueness: {case_sensitive: false}

	# Si avatar obligatoire, mettre presence: true
	
	has_image :avatar

	def to_session
		{id: id}
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]
  skip_before_action :only_signed_in, only: [:species, :index, :show]

  def index
    pet_ids = current_user.followed_pets.pluck(:id)
    if pet_ids.empty?
      @posts = []
    else
      @posts = Post.joins('INNER JOIN pets_posts ON pets_posts.post_id = posts.id').where("pets_posts.pet_id IN (#{pet_ids.join(',')})")
    end
  end

  def species
    # ! renvoie une exception si il y a une erreur
    @species = Species.find_by_slug!(params[:slug])
    @posts = Post.joins(:pets).where(pets: {species_id: @species.id})
  end

  # GET /posts
  # GET /posts.json
  def me
    @posts = current_user.posts.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
    @post.user = current_user
    # @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    # @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, success: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_path, success: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, success: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      p = params.require(:post).permit(:name, :content, :image_file, pet_ids: [])
      p[:pet_ids] = current_user.pets.where(id: p[:pet_ids]).pluck(:id)
      p
    end
end

app/views/posts/_form.html.erb
<%= form_for post, html: {class: 'form-horizontal'} do |f| %>
  <% if post.errors.any? %>
	<div class="alert alert-danger">
	  <ul>
	  <% post.errors.full_messages.each do |message| %>
		<li><%= message %></li>
	  <% end %>
	  </ul>
	</div>
  <% end %>

  <div class="form-group">
	<%= f.label :name, class: 'col-md-4 control-label' %>
	<div class="col-md-8">
	  <%= f.text_field :name, class: 'form-control' %>
	</div>
  </div>

  <div class="form-group">
	<%= f.label :image_file, 'Image', class: 'col-md-4 control-label' %>
	<div class="col-md-8">
	  <%= f.file_field :image_file, class: 'form-control' %>
	  <% unless post.new_record? %>
		<%= image_tag post.image_url(:thumb ) %>
	  <% end %>
	</div>
  </div>

  <div class="form-group">
	<%= f.label :pet_ids, 'Animaux' ,class: 'col-md-4 control-label' %>
	<div class="col-md-8">
	  <%= f.select :pet_ids, Pet.pluck(:name, :id), {}, multiple: :true, class: 'form-control' %>
	</div>
  </div>

  <div class="form-group">
	<%= f.label :content, 'Contenu' ,class: 'col-md-4 control-label' %>
	<div class="col-md-8">
	  <%= f.text_area :content, class: 'form-control' %>
	</div>
  </div>

  <div class="form-group">
	<div class="col-md-offset-4 col-md-6">
	  <button type="submit" class="btn btn-primary">
		<%= post.new_record? ? 'Créer' : 'Modifier' %>
	  </button>
	</div>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="<%= klass if local_assigns[:klass] %>">
	<%= link_to post do %>
		<h4><%= post.name %></h4>
		<%= image_tag post.image_url(:thumb), width: '100%' %>
	<% end %>
</div>

app/views/posts/edit.html.erb
<% content_for :content do %>
  <div class="panel panel-default">
    <div class="panel-heading">Modifier <% @post.name %></div>
    <div class="panel-body">
      <%= render 'form', post: @post %>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/profile' %>

app/views/posts/index.html.erb
<% content_for :tab, :posts %>
<% content_for :content do %>

  <h1>Animaux followed :</h1>

  <p class="text-right">
    <a href="<%= new_post_path %>" class="btn btn-primary">Ajouter un Post</a>
  </p>

  <div class="row">
    <% @posts.each do |post| %>
      <div class="col-md-6">
        <%= render post %>
      </div>
    <% end %>
  </div>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/posts/me.html.erb
<% content_for :tab, :me %>
<% content_for :content do %>

  <h1>Gérer les Posts</h1>

  <p class="text-right">
    <a href="<%= new_post_path %>" class="btn btn-primary">Ajouter un Post</a>
  </p>

  <table class="table table-striped">
    <thead>
      <tr>
          <th>Name</th>
          <th>Content</th>
          <th>User</th>
          <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
            <td><%= image_tag post.image_url(:thumb) %></td>
            <td><%= post.name %></td>
            <td><%= post.content %></td>
            <td>
              <%= link_to 'Voir', post, class: 'btn btn-default' %>
              <%= link_to 'Modifier', edit_post_path(post), class: 'btn btn-primary' %>
              <%= link_to 'Supprimer', post, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<%= render template: 'layouts/profile' %>

app/views/posts/new.html.erb
<% content_for :content do %>
  <div class="panel panel-default">
    <div class="panel-heading">Créer Post</div>
    <div class="panel-body">
      <%= render 'form', post: @post %>
    </div>
  </div>
<% end %>

<%= render template: 'layouts/profile' %>

app/views/posts/show.html.erb
<div class="page-header">
	<h1><%= @post.name %></h1>
</div>

<div class="text-center">
	<%= image_tag @post.image_url, width: '100%' %>
</div>

<div class="row">
	<div class="col-md-8">
		<h2>Description :</h2>
		<% if canEdit(@post) %>
			<p>
				<%= link_to 'Modifier', [:edit, @post], class: 'btn btn-primary' %>
				<%= link_to 'Supprimer', @post, class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %>
			<p/
		<% end%>
		<p><%= @post.content %></p>
	</div>
	<div class="col-md-4">
	<h2>Sur cette photo:</h2>
		<ul class="list-group">
			<%= render @post.pets %>
		</ul>
	</div>
</div>

app/views/posts/species.html.erb
<h1>Tous les animaux de type <%= @species.name %></h1>

<div class="row">
  <div class="col-md-8">
    <div class="row">
      <%= render @posts, klass: 'col-md-4' %>
    </div>
  </div>
  <div class="col-md-4">
    <%= render 'shared/sidebar' %>
  </div>
</div>