config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'

  resources :posts do
    collection do
     get 'me'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get '/animaux/:slug', to: 'posts#species', as: :species_posts
  get '/profil', to: 'users#edit', as: :profil
  patch '/profil', to: 'users#update'
  resources :users, only: [:new, :create] do
  	member do
  		get 'confirm'
  	end
  end
  # Sessions
  get '/login', to: 'sessions#new', as: :new_session
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: :destroy_session
  resources :sessions, only: [:new, :create, :destroy]
  resources :passwords, only: [:new, :create, :edit, :update]
  resources :pets do
    resource :subscriptions, only: [:create, :destroy]
  end

  scope 'superadmin', module: 'admin', as: 'admin' do
    resources :species, except: [:show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Petsy</title>
		<%= csrf_meta_tags %>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

		<!-- flatpickr -->
	</head>

	<body>
		<div class="navbar navbar-inverse">
			<div class="container">
				<div class="navbar-header">
					<a href="<%= root_path %>" class="navbar-brand">Petsy</a>
				</div>
	
				<% if user_signed_in? && isAdmin? %>
				<ul class="nav navbar-nav">
					<li>
						<%= link_to 'Gestion des espèces', [:admin, Species] %>
					</li>
				</ul>
				<% end %>
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
								<%= current_user.username %>
								<span class="caret"></span>
							</a>
							<ul class="dropdown-menu" role="menu">
								<li><%= link_to 'Mon profil', profil_path %></li>
								<li><%= link_to 'Se déconnecter', destroy_session_path, data: {method: :delete} %></li>

							</ul>
						</li>
					<% else %>
						<li><a href="<%= new_user_path %>">S'inscrire</a></li>
						<li><a href="<%= new_session_path %>">Se connecter</a></li>
					<% end %>
				</ul>
			</div>
		</div>
		<div class="container">
			<% if flash[:success] %>
				<div class="alert alert-success">
					<%= flash[:success] %>
				</div>
			<% end %>

			<% if flash[:danger] %>
				<div class="alert alert-danger">
					<%= flash[:danger] %>
				</div>
			<% end %>
		</div>
		<div class="container">
			<%= yield %>
		</div>

		<!-- Latest compiled and minified JavaScript -->
		<%= javascript_include_tag 'application', 'data-turbolinks-eval': 'false', 'data-turbolinks-track': 'reload' %>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

	</body>
</html>

app/views/layouts/profile.html.erb
<div class="row">
	<div class="col-md-8">
		<%= debug yield(:tab) %>
		<%= yield(:content) %>
	</div>
	<div class="div col-md-4">
		<div class="list-group">
			<a href="<%= posts_path %>" class="list-group-item <%= yield(:tab) == 'posts' ? ' active' : '' %>">Following</a>
			<a href="<%= me_posts_path %>" class="list-group-item <%= yield(:tab) == 'me' ? ' active' : '' %>">Mes photos</a>
			<a href="<%= pets_path %>" class="list-group-item<%= yield(:tab) == 'pets' ? ' active' : '' %>">Mes animaux</a>
			<a href="<%= profil_path %>" class="list-group-item <%= yield(:tab) == 'profil' ? ' active' : '' %>">Mon compte</a>
		</div>
	</div>
</div>